GCDataRepository Cleanup procedures
googleinterns/step240-2020 pull request #67
Opened 2020-08-31 10:42 UTC by MagoDelBlocco

This PR adds the cleanup procedure, parameters class and scheduling to GCDataRepository from #66 . 

The cleanup procedure is a Runnable() implementation, which queries the datastore for all entries older than a date provided by the CleanupParameters class, then deletes those entries.
The CleanupParameters class is a subclass of the GCDataRepository, which contains all the parameters needed for the cleanup procedure (e.g. Entry TTL, cleanup frequency, etc.).
The scheduling is done via the [ScheduledExecutorService](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledExecutorService.html#:~:text=Interface%20ScheduledExecutorService&text=An%20ExecutorService%20that%20can%20schedule,to%20cancel%20or%20check%20execution.) provided by Java.

2020-08-31 11:49 UTC, holounic approved these changes
LGTM

2020-09-01 08:44 UTC, Somae commented
Please add tests. In this case interesting test cases would include making sure the procedure doesn't delete too many entries for example. This is good to have for the future to make sure this never regresses and relevant data is deleted.

2020-09-01 08:45 UTC, Somae requested changes
Please add tests. In this case interesting test cases would include making sure the procedure doesn't delete too many entries for example. This is good to have for the future to make sure this never regresses and relevant data is deleted.

2020-09-01 09:54 UTC, MagoDelBlocco commented
> Please add tests.
This is in the scope of #70, which will get merged in #66. The order of merging should be #67 -> #70 -> #66.

2020-09-01 17:04 UTC, krasimir-google commented on src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
> +  private final ScheduledExecutorService cleanScheduler = Executors.newScheduledThreadPool(1);
Consider using Spring's `@Scheduled` [functionality](https://www.baeldung.com/spring-scheduled-tasks), more specifically its [cron expressions](https://www.baeldung.com/spring-scheduled-tasks) version for scheduling.
[Cron expressions](https://en.wikipedia.org/wiki/Cron) are a versatile, industry-standard way to specify periodic schedules and Spring's `@Scheduled` makes it easy to hook up (you just need a void method that takes no params to annotate; you don't even need to wrap it in Runnable as you need here).

An additional advantage of a cron-based approach compared to using a ScheduledExecutorService is that when we have to re-deploy or re-start the application, the cron-based approach would not us to perform cause additional cleanup calls (as ScheduledExecutorService does not remember the last time it ran if an app gets restarted or re-deployed).

2020-09-02 15:49 UTC, krasimir-google reviewed
Left some suggestions for the test cases.

2020-09-02 15:49 UTC, krasimir-google commented on src/test/java/com/google/graphgeckos/dashboard/storage/DatastoreRepositoryTests.java
> +    // Test deletion when entry is older than the timestamp
I'd suggest splitting this `@Test` method up into separate `@Test` methods, each corresponding to 1 section of the code. You can base the names to the test methods on your comments.

2020-09-02 15:49 UTC, krasimir-google commented on src/test/java/com/google/graphgeckos/dashboard/storage/DatastoreRepositoryTests.java
> +    Assert.assertTrue(storage.getRevisionEntry("1") == null);
Prefer [`assertNull`](https://junit.org/junit4/javadoc/4.8/org/junit/Assert.html#assertNull(java.lang.Object)), here and in other places; it's more specific and it prints more useful error messages
Similarly, please split up the other one

2020-09-02 15:49 UTC, krasimir-google commented on src/test/java/com/google/graphgeckos/dashboard/storage/DatastoreRepositoryTests.java
> +    Assert.assertFalse(storage.getRevisionEntry("1") == null);
prefer [`assertNotNull`](https://junit.org/junit4/javadoc/4.8/org/junit/Assert.html#assertNotNull(java.lang.Object)), here and in other places

2020-09-02 15:50 UTC, krasimir-google commented on src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
> +  private final DataRetentionParameters dataRetentionParameters;
I believe we don't need the `cleanScheduler` and the `dataRetentionParameters` members anymore.

2020-09-02 15:52 UTC, krasimir-google commented on src/main/java/com/google/graphgeckos/dashboard/storage/DatastoreRepository.java
> +   * amount of time. During this operation, the GCDataRepository can be queried, but
```suggestion
   * amount of time. During this operation, this repository can be queried, but
```
(GCDataRepository is the obsolete name of this class)

2020-09-07 10:33 UTC, MagoDelBlocco commented
GCP has a setting for Datastore Entity lifecycles.

2020-09-07 10:33 UTC, closed without merging